apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-backend-10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-backend-10
  template:
    metadata:
      labels:
        app: todo-app-backend-10
    spec:
      containers:
      - name: backend
        # このプレースホルダーがワークフローによって置換されます
        image: __IMAGE_NAME_PLACEHOLDER__
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-backend-svc-10
spec:
  type: LoadBalancer
  selector:
    app: todo-app-backend-10
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
